# Generated by Django 4.1.2 on 2022-10-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livraison',
            new_name='Fiche_reception',
        ),
    ]
