# Generated by Django 4.1.2 on 2022-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0002_rename_livraison_fiche_reception'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Echantillon',
            new_name='Fiche_analyse',
        ),
    ]
