# Generated by Django 4.1.2 on 2022-10-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0003_rename_echantillon_fiche_analyse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id',
        ),
        migrations.AlterField(
            model_name='commande',
            name='lv_commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='copeol_app.camion'),
        ),
    ]
