# Generated by Django 4.1.2 on 2022-10-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0004_remove_commande_id_alter_commande_lv_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='lv_livraison',
        ),
        migrations.RemoveField(
            model_name='fiche_reception',
            name='id',
        ),
        migrations.AddField(
            model_name='commande',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_reception',
            name='lv_livraison',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='copeol_app.camion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='lv_commande',
            field=models.CharField(max_length=6),
        ),
    ]
