# Generated by Django 4.1.2 on 2022-10-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0005_remove_camion_lv_livraison_remove_fiche_reception_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche_reception',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiche_reception',
            name='lv_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='copeol_app.commande'),
        ),
    ]
