# Generated by Django 4.1.2 on 2022-10-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0007_commande_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='name',
        ),
    ]
