# Generated by Django 4.1.2 on 2022-10-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copeol_app', '0008_remove_commande_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camion',
        ),
    ]
