# Generated by Django 4.1.2 on 2022-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0009_delete_camion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiche_analyse",
            name="poids",
        ),
        migrations.RemoveField(
            model_name="fiche_analyse",
            name="poids_net",
        ),
        migrations.AddField(
            model_name="fiche_analyse",
            name="graines_defectueuses",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fiche_analyse",
            name="variete",
            field=models.CharField(
                choices=[("varieté2", "varieté1"), ("varieté2", "varieté2")],
                default=0,
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
