# Generated by Django 4.1.2 on 2022-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0010_remove_fiche_analyse_poids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiche_analyse",
            name="variete",
            field=models.CharField(
                choices=[("Coques", "Décortiquées"), ("Coques", "Coques")],
                max_length=15,
            ),
        ),
    ]
