# Generated by Django 4.1.2 on 2022-10-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0011_alter_fiche_analyse_variete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fiche_analyse",
            old_name="graines_defectueuses",
            new_name="taux_graines_defectueuses",
        ),
    ]
