# Generated by Django 4.1.2 on 2022-10-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "copeol_app",
            "0012_rename_graines_defectueuses_fiche_analyse_taux_graines_defectueuses",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="poids",
        ),
    ]
