# Generated by Django 4.1.2 on 2022-10-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0013_remove_commande_poids"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche_analyse",
            name="fiche_reception",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="copeol_app.fiche_reception",
            ),
        ),
    ]
