# Generated by Django 4.1.2 on 2022-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0014_fiche_analyse_fiche_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="pnc",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facture",
            name="provenance",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
