# Generated by Django 4.1.2 on 2022-10-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0015_facture_pnc_facture_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="fiche_analyse",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facture",
            name="frais_dechargement",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facture",
            name="frais_livraison",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facture",
            name="prix_unitaire",
            field=models.IntegerField(default=0),
        ),
    ]
