# Generated by Django 4.1.2 on 2022-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copeol_app", "0016_facture_fiche_analyse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiche_analyse",
            name="variete",
            field=models.CharField(
                choices=[("Décortiquées", "Décortiquées"), ("Coques", "Coques")],
                max_length=15,
            ),
        ),
    ]
